backend:
  name: git-gateway
  branch: main
media_folder: "static/images"
collections:
  - name: "about" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "about" # Used in the UI, ie.: "New Post"
    folder: "content/english/about" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "About bg image1", name: "aboutbgimage1", widget: "image" }
      - { label: "About title", name: "abouttitle", widget: "string" }
      - { label: "About content", name: "aboutcontent", widget: "string" }
      - { label: "Content", name: "content", widget: "text" }
      - { label: "Draft", name: "draft", widget: "boolean" }